# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Xin Lab"
title:              "Xin Lab at the Macquarie University"
description:        "The Xin Lab is a psycholinguistics Lab."


# URL
url:                “https://xinlab-clue.github.io”
baseurl:            "https://xinlab-clue.github.io"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html
#permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
#  - name:           "home"
#    href:           "/"
  - name:           "about"
    href:           "/about/"
  - name:           "publications"
    href:           "/publications/"
  - name:           "people"
    href:           "/people/"
  # - name:           "blog"
    # href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts/"
  - name:           "lab talks"
    href:           "/presentations/"
  - name:           "research opportunities"
    href:           "/research_opportunities/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    #permalink: /people/:title/index.html
    permalink: /people/:title/
